services:
  proxy:
    image: envoyproxy/envoy:v1.33-latest
    volumes:
      - ./proxy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8070:8070"
      - "9901:9901"
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "9090:9090"
