// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "dashboard.proto" (package "dashboard", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { Dashboard } from "./dashboard";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetGreetingResponse } from "./dashboard";
import type { GetGreetingRequest } from "./dashboard";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service dashboard.Dashboard
 */
export interface IDashboardClient {
    /**
     * @generated from protobuf rpc: GetGreeting(dashboard.GetGreetingRequest) returns (dashboard.GetGreetingResponse);
     */
    getGreeting(input: GetGreetingRequest, options?: RpcOptions): UnaryCall<GetGreetingRequest, GetGreetingResponse>;
}
/**
 * @generated from protobuf service dashboard.Dashboard
 */
export class DashboardClient implements IDashboardClient, ServiceInfo {
    typeName = Dashboard.typeName;
    methods = Dashboard.methods;
    options = Dashboard.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: GetGreeting(dashboard.GetGreetingRequest) returns (dashboard.GetGreetingResponse);
     */
    getGreeting(input: GetGreetingRequest, options?: RpcOptions): UnaryCall<GetGreetingRequest, GetGreetingResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetGreetingRequest, GetGreetingResponse>("unary", this._transport, method, opt, input);
    }
}
